workspace 'RutaSegura'

def rx
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
end

use_frameworks!

target 'RutaSegura' do

  rx
  pod 'SwiftLint'


  target 'RutaSeguraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RutaSeguraUITests' do
    # Pods for testing
  end

end




# Pods for NetworkLayer
target 'NetworkLayer' do
  use_frameworks!
  project 'Core/NetworkLayer/NetworkLayer'
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'SwiftLint'

  target 'NetworkLayerTests' do
    pod 'RxBlocking', '~> 5.0'
    inherit! :search_paths
  end

end
