# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RutaSegura' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RutaSegura
  pod 'SwiftLint'


  target 'RutaSeguraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RutaSeguraUITests' do
    # Pods for testing
  end

end
